server:
  port: 8889

spring:
  cloud:

    config:
      server:
        git:
          uri: "https://github.com/alivolkansahin/config-server-repouygulama1.git"
          default-label: main #eğer başka bir branch olsaydı o branchin adını yazmak gerekiyordu
          skip-ssl-validation: true
          refresh-rate: 10
          username: alivolkansahin
          password: ${Java12_SocialMediaProject_GIT_KEY} # güvenlikten dolayı kendi şifremi açık açık yazamam şifremi, generate token yaptık github üzerinden