server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway-service
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/api/v1/auth/**
          uri: http://localhost:9090
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/authservice
        - id: user-service
          predicates:
            - Path=/api/v1/user/**
          uri: http://localhost:9091
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/userservice
        - id: post-service
          predicates:
            - Path=/api/v1/post/**
          uri: http://localhost:9092
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/postservice
      default-filters: # burayı dökümantasyondan öğrendik
        # http://localhost/auth/findbyid/1
        # (?<segment>.*)   -->  auth/findbyid/1
        #   /$\{segment}   -->  http://localhost:9090/auth/findbyid/1
        - RewritePath=/(?<segment>.*), /$\{segment} # RewritePath=/(?<segment>.*),/api/v1/$\{segment}   eğer çoğu urlde kullandığınız statik değerler var ise, api/v1 gibi...
#    config:
#      enabled: false # Eğer config serverım varsa ve ona rağmen ben ayarları burdan çekiyorsam bunu böyle belirtmem gerekiyor (tabi config-server içerisindeyken olmaz böyle diye yoruma aldık)
