server:
  port: 9090

spring:
  rabbitmq: # rabbitmq 12 aralık salı
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/SocialMedia_AuthDb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:  # 14 Aralık Perşembe Redis
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: volkan
      password: 123

jwt:
  secretKey: ${Java12_SocialMediaProject_SecretKey}
  issuer: ${Java12_SocialMediaProject_Issuer}
rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  activation-queue: activationQueue
  mail-queue: mailQueue
  registerElastic-queue: registerElasticQueue
  register-bindingKey: registerBindingKey
  activation-bindingKey: activationBindingKey
  mail-bindingKey: mailBindingKey
  registerElastic-bindingKey: registerElasticBindingKey

#redis:  # configurasyon sınıfı kullanacaksan bunu açmalısın @value için
#  host: localhost
#  port: 6379