server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/SocialMedia_AuthDb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${Java12_SocialMediaProject_SecretKey}
  issuer: ${Java12_SocialMediaProject_Issuer}