server:
  port: 9094

spring:
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service

rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  activation-queue: activationQueue
  mail-queue: mailQueue
  registerElastic-queue: registerElasticQueue
  register-bindingKey: registerBindingKey
  activation-bindingKey: activationBindingKey
  mail-bindingKey: mailBindingKey
  registerElastic-bindingKey: registerElasticBindingKey