server:
  port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  mail: # mail 13 aralık çarşamba
    host: smtp.gmail.com
    port: 587
    username: avolkan.shn@gmail.com
    password: hvpn djwp ugvl uvzd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  activation-queue: activationQueue
  mail-queue: mailQueue
  register-bindingKey: registerBindingKey
  activation-bindingKey: activationBindingKey
  mail-bindingKey: mailBindingKey