server:
  port: 9092

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/SocialMedia_PostDb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${Java12_SocialMediaProject_SecretKey}
  issuer: ${Java12_SocialMediaProject_Issuer}