server:
  port: 9091

spring:
  rabbitmq: # rabbitmq 12 aralık salı
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service #uniquelik mevzusu YOK, sadece takip için kendi isimlendirmen gibi düşün burayı...
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/SocialMedia_UserDb
#    # 20.12.2023 WEDNESDAY İLE ARTIK MONGODB YE GEÇTİK ONDAN YORUM SATIRINA ALDIK, MONGODB AYARLARI EKLEYECEĞİZ
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  cache: # 14 Aralık Perşembe Redis
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
    mongodb: # 20.12.2023 WEDNESDAY İLE ARTIK MONGODB YE GEÇTİK ONDAN YORUM SATIRINA ALDIK, MONGODB AYARLARI EKLEYECEĞİZ
      host: localhost
      port: 27020
      username: java12user
      password: root
      database: UserDb

jwt:
  secretKey: ${Java12_SocialMediaProject_SecretKey}
  issuer: ${Java12_SocialMediaProject_Issuer}
rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  activation-queue: activationQueue
  registerElastic-queue: registerElasticQueue
  register-bindingKey: registerBindingKey
  activation-bindingKey: activationBindingKey
  registerElastic-bindingKey: registerElasticBindingKey


#redis:  # configurasyon sınıfı kullanacaksan bunu açmalısın @value için
#  host: localhost
#  port: 6379